# 0. Importando bibliotecas

In [3]:
pip install pandas

Collecting pandas
  Using cached pandas-3.0.2-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=2.3.3 (from pandas)
  Using cached numpy-2.4.4-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.2-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
Using cached numpy-2.4.4-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.4.4 pandas-3.0.2

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd

# 1. Tratamento

In [41]:
path_df_balanco_dia ="dataset_principal/balanco_servico_dia.csv"

df_balanco_dia = pd.read_csv(path_df_balanco_dia)

df_balanco_dia.head()

,data,servico,consorcio,km_apurada,receita_total_esperada,receita_tarifaria_esperada,subsidio_esperado,subsidio_glosado,receita_total_aferida,receita_tarifaria_aferida,valor_subsidio_pago,saldo,versao,datetime_ultima_atualizacao,id_execucao_dbt
0,2024-02-07,SN483,Internorte,526.046,4697.59078,2572.36494,2125.22584,2125.22584,1005.89,1005.89,0.0,-1566.47494,933971ef4769872f2b34a01c0fa8ae22488bdb85,2025-07-15 21:03:58.678701,9b1a0f21-cffb-42cf-ad0c-edf953ee336e
1,2024-02-07,313,Internorte,2839.089,25353.06477,13883.14521,11469.91956,11469.91956,17034.77,17034.77,0.0,3151.62479,933971ef4769872f2b34a01c0fa8ae22488bdb85,2025-07-15 21:03:58.678701,9b1a0f21-cffb-42cf-ad0c-edf953ee336e
2,2024-02-07,385,Internorte,119.790,1069.72470,585.77310,483.95160,483.95160,998.68,998.68,0.0,412.90690,933971ef4769872f2b34a01c0fa8ae22488bdb85,2025-07-15 21:03:58.678701,9b1a0f21-cffb-42cf-ad0c-edf953ee336e
3,2024-02-07,920,Internorte,3377.366,30159.87838,16515.31974,13644.55864,13644.55864,24611.48,24611.48,0.0,8096.16026,933971ef4769872f2b34a01c0fa8ae22488bdb85,2025-07-15 21:03:58.678701,9b1a0f21-cffb-42cf-ad0c-edf953ee336e
4,2024-02-07,249,Internorte,5411.151,48321.57843,26460.52839,21861.05004,21861.05004,53311.40,53311.40,0.0,26850.87161,933971ef4769872f2b34a01c0fa8ae22488bdb85,2025-07-15 21:03:58.678701,9b1a0f21-cffb-42cf-ad0c-edf953ee336e

In [42]:
df_balanco_dia_tratado = df_balanco_dia.drop(columns=['km_apurada','versao','datetime_ultima_atualizacao','id_execucao_dbt'])
df_balanco_dia_tratado.head()

,data,servico,consorcio,receita_total_esperada,receita_tarifaria_esperada,subsidio_esperado,subsidio_glosado,receita_total_aferida,receita_tarifaria_aferida,valor_subsidio_pago,saldo
0,2024-02-07,SN483,Internorte,4697.59078,2572.36494,2125.22584,2125.22584,1005.89,1005.89,0.0,-1566.47494
1,2024-02-07,313,Internorte,25353.06477,13883.14521,11469.91956,11469.91956,17034.77,17034.77,0.0,3151.62479
2,2024-02-07,385,Internorte,1069.72470,585.77310,483.95160,483.95160,998.68,998.68,0.0,412.90690
3,2024-02-07,920,Internorte,30159.87838,16515.31974,13644.55864,13644.55864,24611.48,24611.48,0.0,8096.16026
4,2024-02-07,249,Internorte,48321.57843,26460.52839,21861.05004,21861.05004,53311.40,53311.40,0.0,26850.87161

In [43]:
path_df_servico_historico = "dataset_principal/sumario_servico_dia_historico.csv"

df_servico_historico = pd.read_csv(path_df_servico_historico)

df_servico_historico.head()

,data,tipo_dia,consorcio,servico,vista,viagens,km_apurada,km_planejada,perc_km_planejada,valor_subsidio_pago,valor_penalidade,datetime_ultima_atualizacao
0,2024-04-06,Sabado,Santa Cruz,383,Realengo - Praça da República,154,5154.242,6056.38,85.10,14980.27260,0.0,2025-09-22 12:32:31.291432
1,2024-04-06,Sabado,Santa Cruz,SN898,Sepetiba - Campo Grande,14,438.038,377.51,116.03,1769.67352,0.0,2025-09-22 12:32:31.291432
2,2024-04-06,Sabado,Santa Cruz,853,Vila Kennedy - Terminal Mato Alto,72,1738.368,1786.66,97.30,7023.00672,0.0,2025-09-22 12:32:31.291432
3,2024-04-06,Sabado,Santa Cruz,SN885,Terminal Mato Alto - Santa Cruz,17,297.490,279.71,106.36,990.32740,0.0,2025-09-22 12:32:31.291432
4,2024-04-06,Sabado,Santa Cruz,845,Cantagalo - Terminal Campo Grande,38,265.620,231.10,114.94,1073.10480,0.0,2025-09-22 12:32:31.291432

In [44]:
df_servico_historico_tratado = df_servico_historico.drop(columns=['datetime_ultima_atualizacao'])

In [50]:
df_final = df_servico_historico_tratado.merge(df_balanco_dia_tratado, on=['servico', 'data','consorcio','valor_subsidio_pago'], how='inner')

In [51]:
df_final.head()

,data,tipo_dia,consorcio,servico,vista,viagens,km_apurada,km_planejada,perc_km_planejada,valor_subsidio_pago,valor_penalidade,receita_total_esperada,receita_tarifaria_esperada,subsidio_esperado,subsidio_glosado,receita_total_aferida,receita_tarifaria_aferida,saldo
0,2024-04-06,Sabado,Santa Cruz,SN885,Terminal Mato Alto - Santa Cruz,17,297.490,279.71,106.36,990.32740,0.0,2656.58570,1454.72610,1201.85960,211.53220,1370.44740,380.12,-1074.60610
1,2024-04-06,Sabado,Santa Cruz,845,Cantagalo - Terminal Campo Grande,38,265.620,231.10,114.94,1073.10480,0.0,2371.98660,1298.88180,1073.10480,0.00000,1488.15480,415.05,-883.83180
2,2024-04-06,Sabado,Santa Cruz,868,Urucânia - Campo Grande,61,736.888,798.70,92.26,2728.62541,0.0,6580.40984,3603.38232,2977.02752,248.40211,4647.28541,1918.66,-1684.72232
3,2024-04-06,Sabado,Santa Cruz,788,Terminal Campo Grande - Terminal Deodoro,30,710.805,663.42,107.14,2412.94604,0.0,6347.48865,3475.83645,2871.65220,458.70616,5542.48604,3129.54,-346.29645
4,2024-04-06,Sabado,Santa Cruz,936,Campo Grande - Cidade Universitária,22,1093.180,993.80,110.00,4175.94760,0.0,9762.09740,5345.65020,4416.44720,240.49960,6301.78760,2125.84,-3219.81020

In [52]:
df_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 7595 entries, 0 to 7594
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   data                        7595 non-null   str
 1   tipo_dia                    7595 non-null   str
 2   consorcio                   7595 non-null   str
 3   servico                     7595 non-null   str
 4   vista                       7595 non-null   str
 5   viagens                     7595 non-null   int64
 6   km_apurada                  7595 non-null   float64
 7   km_planejada                7595 non-null   float64
 8   perc_km_planejada           7595 non-null   float64
 9   valor_subsidio_pago         7595 non-null   float64
 10  valor_penalidade            7595 non-null   float64
 11  receita_total_esperada      7595 non-null   float64
 12  receita_tarifaria_esperada  7595 non-null   float64
 13  subsidio_esperado           7595 non-null   float64
 14  subsidio_glosado            7595 non-null   float64
 15  receita_total_aferida       7595 non-null   float64
 16  receita_tarifaria_aferida   7595 non-null   float64
 17  saldo                       7595 non-null   float64
dtypes: float64(12), int64(1), str(5)
memory usage: 1.0 MB

In [ ]:
# TODO Resultados
# 1. Plotar um gráfico para series temporais comparando a relação de km_planejado e apurado, e talvez até um valor de receita com o balanco_servico_dias
# 2. Plotar um gráfico de subsidio_glosado e tentar verificiar anomalidades e fraudes em serviços (possíveis linhas fantasmas)
# 3. Plotar um gráfico com os serviços e consorcios que geram mais receita
# 4. Plotar um gráfico com os serviços com saldo negativo
# 5. Tentar achar uma relação entre linhas de ônibus onde o km_apurado é muito alto e possíveis problemas de passagem no csv trajeto alternativo